DROP DATABASE IF EXISTS VinylCollection;
GO

CREATE DATABASE VinylCollection;
GO

USE VinylCollection;
GO

DROP TABLE IF EXISTS Vinyl;
GO

CREATE TABLE Vinyl (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Title VARCHAR(50) NOT NULL,
	ReleaseDate DATE NULL,
	Label VARCHAR(50) NULL,
	Producer VARCHAR(50) NULL,
	CatalogNumber VARCHAR(20) NULL,
	ShelfNumber INT NULL,
	Condition VARCHAR(100) NULL,
	CONSTRAINT CkVinyl_ShelfNumber CHECK (ShelfNumber >= 0)
);
GO

DROP TABLE IF EXISTS Musician;
GO

CREATE TABLE Musician (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Country VARCHAR(60) NULL,
	CONSTRAINT UnMusician_Name UNIQUE (Name)
);
GO

DROP TABLE IF EXISTS VinylMusician;
GO

CREATE TABLE VinylMusician (
	VinylID INT NOT NULL,
	MusicianID INT NOT NULL,
	PRIMARY KEY (VinylID, MusicianID),
	CONSTRAINT FkVinylMusician_VinylID FOREIGN KEY (VinylID)
		REFERENCES Vinyl(ID)
		ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT FkVinylMusician_MusicianID FOREIGN KEY (MusicianID)
		REFERENCES Musician(ID)
		ON UPDATE CASCADE ON DELETE NO ACTION
);
GO

DROP TABLE IF EXISTS Band;
GO

CREATE TABLE Band (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	FormationDate DATE NULL,
	DisbandedDate DATE NULL,
	MusicianID INT NOT NULL,
	CONSTRAINT CkBand_Dates CHECK (DisbandedDate >= FormationDate),
	CONSTRAINT FkBand_MusicianID FOREIGN KEY (MusicianID)
		REFERENCES Musician(ID)
		ON UPDATE CASCADE ON DELETE NO ACTION
);
GO

DROP TABLE IF EXISTS Instrumentalist;
GO

CREATE TABLE Instrumentalist (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Instrument VARCHAR(50) NULL,
	MusicianID INT NOT NULL,
	CONSTRAINT FkInstrumentalist_MusicianID FOREIGN KEY (MusicianID)
		REFERENCES Musician(ID)
		ON UPDATE CASCADE ON DELETE NO ACTION
);
GO

DROP TABLE IF EXISTS Singer;
GO

CREATE TABLE Singer (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	VocalClassification VARCHAR(50) NULL,
	MusicianID INT NOT NULL,
	CONSTRAINT FkSinger_MusicianID FOREIGN KEY (MusicianID)
		REFERENCES Musician(ID)
		ON UPDATE CASCADE ON DELETE NO ACTION
);
GO

DROP TABLE IF EXISTS Song;
GO

CREATE TABLE Song (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Title VARCHAR(50) NOT NULL,
	Duration VARCHAR(10) NULL,
	CONSTRAINT CkSong_Duration CHECK (Duration > 0)
);
GO

DROP TABLE IF EXISTS MusicianSong;
GO

CREATE TABLE MusicianSong (
	MusicianID INT NOT NULL,
	SongID INT NOT NULL,
	PRIMARY KEY (MusicianID, SongID),
	CONSTRAINT FkMusicianSong_MusicianID FOREIGN KEY (MusicianID)
		REFERENCES Musician(ID)
		ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT FkMusicianSong_SongID FOREIGN KEY (SongID)
		REFERENCES Song(ID)
		ON UPDATE CASCADE ON DELETE NO ACTION
);
GO

DROP TABLE IF EXISTS Genre;
GO

CREATE TABLE Genre (
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Description VARCHAR(150) NULL,
	CONSTRAINT UnGenre_Name UNIQUE (Name)
);
GO

DROP TABLE IF EXISTS SongGenre;
GO

CREATE TABLE SongGenre (
	SongID INT NOT NULL,
	GenreID INT NOT NULL,
	PRIMARY KEY (SongID, GenreID),
	CONSTRAINT FkSongGenre_SongID FOREIGN KEY (SongID)
		REFERENCES Song(ID)
		ON UPDATE CASCADE ON DELETE NO ACTION,
	CONSTRAINT FkSongGenre_GenreID FOREIGN KEY (GenreID)
		REFERENCES Genre(ID)
		ON UPDATE CASCADE ON DELETE NO ACTION
);
GO